#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include: ../../ironic-common/tasks/_set_directories.yml
  vars:
    ironic_pkg_result: "{{ ardana_notify_ironic_conductor_install_result }}"

- name: ironic-conductor | configure | create directories required by
        ironic-conductor
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ironic_user }}"
    group: "{{ ironic_group }}"
    mode: 0775
  with_items:
    - "{{ ironic_images.path }}"
    - "{{ ironic_images.instance_master_path }}"

- include: ../../ironic-common/tasks/_write_conf.yml
  become: yes
  src: "ironic-conductor.conf.j2"
  dest: "{{ ironic_service_conf_dir }}/ironic-conductor.conf"

- name: ironic-conductor | configure | notify on ironic-conductor.conf change
  command: /bin/true
  register: ardana_notify_ironic_conductor_restart_required
  when: write_conf_result.changed

- name: ironic-conductor | configure | Create Apache vhost config for Ironic
  become: yes
  template:
    src: "ironic.conf.j2"
    dest: "{{ apache2_vhost_dir }}/ironic.vhost"
    mode: 0644
  register: ardana_notify_ironic_conductor_apache_reload

- name: ironic-conductor | configure | Setup ironic user to allow sudo to run
        ironic-rootwrap without password
  become: yes
  template:
    src: "ironic-rootwrap.j2"
    dest: /etc/sudoers.d/ironic-rootwrap
    owner: root
    group: root
    mode: 0644
    validate: 'visudo -cf %s'

- name: ironic-conductor | configure | Create a symbolic link between
        filesystem and venv for ironic-rootwrap
  become: yes
  file:
    src: "{{ ironic_service_bin_dir }}/ironic-rootwrap"
    dest: /usr/local/bin/ironic-rootwrap
    owner: "{{ ironic_user }}"
    group: "{{ ironic_group }}"
    force: yes
    state: link

- name: ironic-conductor | configure | stop and disable the default tftpd
        service
  become: yes
  service: name="{{ ironic_conductor_tftp_service }}" state=stopped enabled=no

- name: ironic-conductor | configure | disable the default tftpd
  become: yes
  shell: "systemctl disable {{ ironic_conductor_tftp_service }}.service"

- name: ironic-conductor | configure | Creating map-file
  become: yes
  template:
    src: "map-file.j2"
    dest: "{{ ironic_images.path }}/map-file"
    owner: "{{ ironic_user }}"
    group: "{{ ironic_group }}"
    mode: 0644

- name: ironic-conductor | configure | Creating /etc/xinetd.d/tftp
  become: yes
  template:
    src: "tftp.j2"
    dest: "/etc/xinetd.d/tftp"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - restart xinetd

- name: ironic-conductor | configure | copy ipxe files
  become: yes
  command: cp "{{ item.src }}" "{{ item.dest }}" creates="{{ item.dest }}"
  with_items: ironic_conductor_ipxe_files

- name: ironic-conductor | configure | copy ipxe files
  file:
    path: "{{ item.dest }}"
    owner: "{{ ironic_user }}"
    group: "{{ ironic_user }}"
    mode: 0644
  become: yes
  with_items: ironic_conductor_ipxe_files

- include: ../../ironic-common/tasks/configure.yml
  become: yes
