#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Install Ironic Conductor

- name:  ironic-conductor | start | Enable Ironic vhost
  become: yes
  file:
    src: "{{ apache2_vhost_dir }}/ironic.vhost"
    dest: "{{ apache2_vhost_dir }}/ironic.conf"
    state: link
  register: ardana_notify_ironic_conductor_apache_reload

# Make sure iSCSI Daemon process is running. This is needed by the classic
# PXE drivers (i.e. pxe_ipmitool)
- name: ironic-conductor | start | Start iscsid
  become: yes
  service:
    name: iscsid
    enabled: yes
    state: started
  register: ardana_notify_ironic_conductor_apache_reload

- name: ironic-conductor  | start | Restart or reload apache
  include: "{{ playbook_dir }}/roles/FND-AP2/tasks/start_reload.yml"
  vars:
    apache_reload_requested: "{{
      ardana_notify_ironic_conductor_apache_reload is defined and
      ardana_notify_ironic_conductor_apache_reload.changed }}"
    apache_restart_requested: "{{
      ardana_notify_ironic_common_restart_required is defined and
      ardana_notify_ironic_common_restart_required.changed }}"

- name: ironic-conductor | start | activate the latest installed version
  become: yes
  install_package:
    name: ironic
    service: ironic-conductor
    activate: act_on
    version: "{{ ardana_notify_ironic_conductor_install_result.version }}"
  when: ardana_notify_ironic_conductor_install_result is defined

- name: ironic-conductor | start | register persistent fact of activate
  command: /bin/true
  register: ardana_notify_ironic_conductor_restart_required
  when: (ardana_notify_ironic_conductor_install_result is defined and
        ardana_notify_ironic_conductor_install_result.changed)

- name: ironic-conductor | start | restart ironic-conductor service
  become: yes
  service: name=ironic-conductor state=restarted
  when: (ardana_notify_ironic_common_restart_required is defined and
        ardana_notify_ironic_common_restart_required.changed
        ) or (ardana_notify_ironic_conductor_restart_required is defined and
        ardana_notify_ironic_conductor_restart_required.changed)

- name: ironic-conductor | start | start ironic-conductor service
  become: yes
  service: name=ironic-conductor state=started
