#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: ironic-common | deploy-image-upload | check for iso
  shell: >
    OS_IDENTITY_API_VERSION=3 openstack
    --os-username {{ ironic_glance.admin_user }}
    --os-password {{ ironic_glance.admin_password }}
    --os-tenant-name {{ ironic_keystone_admin.tenant_name }}
    --os-auth-url {{ ironic_cnd_admin.auth_uri }}
    --os-region-name {{ ironic_region }}
    --os-user-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-project-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-interface internal
    image list | grep -w
    "ir-deploy-iso-{{ ironic_deploy_image.version }}"
    | awk '{print $2}'
  register: iso_image_exists_result

- name: ironic-common | deploy-image-upload |
        skip uploading deploy iso again
  debug:
    msg: "Deploy iso already uploaded"
  when: iso_image_exists_result.stdout != ""

- name: ironic-common | deploy-image-upload | check for ramdisk
        image
  shell: >
    OS_IDENTITY_API_VERSION=3 openstack
    --os-username {{ ironic_glance.admin_user }}
    --os-password {{ ironic_glance.admin_password }}
    --os-tenant-name {{ ironic_keystone_admin.tenant_name }}
    --os-auth-url {{ ironic_cnd_admin.auth_uri }}
    --os-region-name {{ ironic_region }}
    --os-user-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-project-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-interface internal
    image list | grep -w
    "ir-deploy-ramdisk-{{ ironic_deploy_image.version }}"
    | awk '{print $2}'
  register: ramdisk_image_exists_result

- name: ironic-common | deploy-image-upload | skip uploading
        deploy ramdisk again
  debug:
    msg: "Deploy ramdisk already uploaded"
  when: ramdisk_image_exists_result.stdout != ""

- name: ironic-common | deploy-image-upload | check for kernel image
  shell: >
    OS_IDENTITY_API_VERSION=3 openstack
    --os-username {{ ironic_glance.admin_user }}
    --os-password {{ ironic_glance.admin_password }}
    --os-tenant-name {{ ironic_keystone_admin.tenant_name }}
    --os-auth-url {{ ironic_cnd_admin.auth_uri }}
    --os-region-name {{ ironic_region }}
    --os-user-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-project-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-interface internal
    image list | grep -w
    "ir-deploy-kernel-{{ ironic_deploy_image.version }}"
    | awk '{print $2}'
  register: kernel_image_exists_result

- name: ironic-common | deploy-image-upload | skip uploading
        deploy kernel again
  debug:
    msg: "Deploy kernel already uploaded"
  when: kernel_image_exists_result.stdout != ""

- name: ironic-common | deploy-image-upload | Set need_upload_images fact
  set_fact:
    need_upload_images: 'Yes'
  when: ramdisk_image_exists_result.stdout == "" or
        kernel_image_exists_result.stdout == ""  or
        iso_image_exists_result.stdout == ""

- name: ironic-common | deploy-image-upload | update deploy Artifact venv cache
  become: yes
  install_package:
    cache: update
  when: ansible_os_family == 'Debian'

- name: ironic-common | deploy-image-upload | setup deploy Artifact Project
  become: yes
  install_package:
    name: "{{ deploy_images_package_name }}"
    service: ironic-deploy-images
    state: present
  when: need_upload_images is defined and
        ansible_os_family == 'Debian'

- name: ironic-common | deploy-image-upload | setup deploy Artifact Project (Suse)
  become: yes
  package:
    name: "{{ deploy_images_package_name }}"
    state: present
  when: need_upload_images is defined and
        ansible_os_family == 'Suse'

- name: ironic-common | deploy-image-upload | Prepare upload images
  include: _debian_prepare_deploy_images.yml
  when: need_upload_images is defined and
        ansible_os_family == 'Debian'

- name: ironic-common | deploy-image-upload | Prepare upload images (SuSE)
  include: _suse_prepare_deploy_images.yml
  when: need_upload_images is defined and
        ansible_os_family == 'Suse'

- name: ironic-common | deploy-image-upload | Upload deploy ramdisk
  run_once: True
  shell: >
    OS_IDENTITY_API_VERSION=3 openstack
    --os-username {{ ironic_glance.admin_user }}
    --os-password {{ ironic_glance.admin_password }}
    --os-tenant-name {{ ironic_keystone_admin.tenant_name }}
    --os-auth-url {{ ironic_cnd_admin.auth_uri }}
    --os-region-name {{ ironic_region }}
    --os-user-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-project-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-interface internal
    --os-cacert {{ ironic_ca_file }}
    image create
    --container-format ari
    --disk-format ari
    --public
    --file {{ ironic_deploy_image.ramdisk }}
    ir-deploy-ramdisk-{{ ironic_deploy_image.version  }}
  when: ramdisk_image_exists_result.stdout == ""
  register: openstackclient_result
  until: openstackclient_result|success
  retries: 5
  delay: 10

- name: ironic-common | deploy-image-upload | Upload deploy kernel
  run_once: True
  shell: >
    OS_IDENTITY_API_VERSION=3 openstack
    --os-username {{ ironic_glance.admin_user }}
    --os-password {{ ironic_glance.admin_password }}
    --os-tenant-name {{ ironic_keystone_admin.tenant_name }}
    --os-auth-url {{ ironic_cnd_admin.auth_uri }}
    --os-region-name {{ ironic_region }}
    --os-user-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-project-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-interface internal
    --os-cacert {{ ironic_ca_file }}
    image create
    --container-format aki
    --disk-format aki
    --public
    --file {{ ironic_deploy_image.kernel }}
    ir-deploy-kernel-{{ ironic_deploy_image.version }}
  when: kernel_image_exists_result.stdout == ""
  register: openstackclient_result
  until: openstackclient_result|success
  retries: 5
  delay: 10

- name: ironic-common | deploy-image-upload | Upload iso
  run_once: True
  shell: >
    OS_IDENTITY_API_VERSION=3 openstack
    --os-username {{ ironic_glance.admin_user }}
    --os-password {{ ironic_glance.admin_password }}
    --os-tenant-name {{ ironic_keystone_admin.tenant_name }}
    --os-auth-url {{ ironic_cnd_admin.auth_uri }}
    --os-region-name {{ ironic_region }}
    --os-user-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-project-domain-name {{ ironic_keystone_admin.default_domain }}
    --os-interface internal
    --os-cacert {{ ironic_ca_file }}
    image create
    --container-format bare
    --disk-format iso
    --public
    --file {{ ironic_deploy_image.iso }}
    ir-deploy-iso-{{ ironic_deploy_image.version }}
  when: iso_image_exists_result.stdout == ""
  register: openstackclient_result
  until: openstackclient_result|success
  retries: 5
  delay: 10

- name: ironic-common | deploy-image-upload | delete images from tmp
  run_once: True
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ironic_deploy_image.kernel }}"
    - "{{ ironic_deploy_image.ramdisk }}"
    - "{{ ironic_deploy_image.iso }}"
  become: yes
  when: need_upload_images is defined

- name: ironic-common | deploy-image-upload | Remove Transient deploy Artifact
  become: yes
  install_package:
    name: "{{ deploy_images_package_name }}"
    service: ironic-deploy-images
    state: absent
  when: need_upload_images is defined and
        ansible_os_family == 'Debian'

- name: ironic-common | deploy-image-upload | Remove Transient deploy Artifact (Suse)
  become: yes
  zypper:
    name: "{{ deploy_images_package_name }}"
    state: absent
  when: need_upload_images is defined and
        ansible_os_family == 'Suse'
